import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/header/Header";

import "./globals.css";
import NavLinksComp from "./components/header/NavLinks";
import Avatar from "./components/header/Avatar";
import AuthProvider from "./components/providers/SessionProvider";
import FooterComp from "./components/footer/FooterComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-12`}
      >
        <AuthProvider>
          <section className="grid grid-cols-2 w-8xl pt-3 px-12">
            <Header isActivePath={true} />
          </section>
          {children}
          <FooterComp />
        </AuthProvider>
      </body>
    </html>
  );
}
